app:
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  cors:
    origin: ["http://localhost:7007"] # Add the URL of your frontend here
    methods: ["GET", "POST", "PUT", "DELETE", "HEAD", "PATCH"]
    credentials: true
  listen: ':7007'
  database:
    client: pg
    connection:
      host: ${PSQL_HOST}
      port: ${PSQL_PORT}
      user: ${PSQL_USER}
      password: ${PSQL_PASSWORD}
      ssl: ${PSQL_SSL}
    pool:
      min: 2
      max: 10
  logging:
    level: info

auth:
  providers:
    guest: {}

catalog:
  orphanStrategy: delete
  processingInterval: { minutes: 2 }
  providers:
    microsoftGraphOrg:
      default:
        tenantId: ${AUTH_MICROSOFT_TENANT_ID}
        clientId: ${AUTH_MICROSOFT_CLIENT_ID}
        clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
        queryMode: basic
        user:
          loadPhotos: true # Load user photos from Microsoft Graph
          fetch:
            - displayName
            - mail
            - id
            - jobTitle
            - userPrincipalName
        group:
          filter: startsWith(displayName, 'co-idp-launchpad-')
          fetch:
            - displayName
            - description
        userGroupMember:
          filter: startsWith(displayName, 'co-idp-launchpad-')
          includeSubGroups: true
        schedule:
          frequency: PT1M
          timeout: PT10M
    azureDevops:
      templateProvider:
        host: 'dev.azure.com'
        organization: 'essity-projects'
        project: '"Essity Infrastructure Services"'
        repository: 'cet-backstage-templates'
        branch: 'main'
        path: '/templates/*/*template.yaml'
        token: ${AZURE_DEVOPS_TOKEN}
        schedule:
          frequency: { minutes: 2 }
          timeout: { minutes: 10 }
          scope: global
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [ Component, System, API, Resource, Location, Template, User, Group, Domain, Policy]
  locations:
    - type: url
      target: https://dev.azure.com/essity-projects/Essity%20Infrastructure%20Services/_git/cet-backstage-templates?path=/locations/cet-template-location.yaml
      rules:
        - allow: [ Component, System, API, Resource, Location, Template, User, Group, Domain, Policy]
      schedule:
        frequency: { minutes: 1 }
        timeout: { minutes: 10 }